baseURL = "https://emino.app/"
languageCode = "en-us"
title = "Emino.App's, Art's & Articles by Emin Mahrt"
theme = "PaperMod"

[params]
dateFormat = "January 2, 2006"
env = "production"
title = "Emino.App's, Art's & Articles by Emin Mahrt"
description = "Karibu to Emin Henri Mahrt's"
keywords = ["blog", "art", "articles", "technology", "development"]
author = "Emin Henri Mahrt"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true

[params.homeInfoParams]
Title = "Karibu to Emin Henri Mahrt's"
Content = "Apps, Art & Articles"

[[params.socialIcons]]
name = "github"
url = "https://github.com/eminogrande"

[[params.socialIcons]]
name = "email"
url = "mailto:emin@nuri.com"

[menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableXML = true
minifyOutput = true
