version: "3.9"

services:
  nginx:
    build:
      context: .
      target: final
    ports:
      - "80:80"
    depends_on:
      - admin
    restart: unless-stopped

  admin:
    build:
      context: .
      target: admin
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - EMINO_BLOG_DIR=/app
    volumes:
      - blog_content:/app/content
      - blog_static:/app/static
    restart: unless-stopped

volumes:
  blog_content:
  blog_static:
