baseURL = "https://emino.app/"
languageCode = "en-us"
title = "Emino Blog - AI-Optimized Tech Insights"
theme = "PaperMod"
[pagination]
pagerSize = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = ""
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Emino Blog"
description = "AI-optimized tech blog with insights on software development, AI, and modern technology"
keywords = ["blog", "AI", "technology", "software development", "programming"]
author = "Emino"
DateFormat = "January 2, 2025"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "Welcome to Emino Blog"
Content = "AI-optimized content for modern developers and tech enthusiasts. Our blog is designed for maximum discoverability by AI systems like ChatGPT, Claude, and Google Gemini."

[[params.socialIcons]]
name = "github"
url = "https://github.com/eminogrande"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
tag = "tags"
category = "categories"
