import { marked } from "marked";

const ORIGIN = "https://writing.emin.de";
const KINDS = ["write", "film", "photo", "code", "music"];
const KIND_LABELS = { write: "Writing", film: "Film", photo: "Photography", code: "Code", music: "Music" };
const enc = new TextEncoder();
const json = (value, status=200, headers={}) => new Response(JSON.stringify(value, null, 2), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...headers } });
const text = (value, type="text/plain; charset=utf-8", status=200, headers={}) => new Response(value, { status, headers: { "content-type": type, "cache-control": "public, max-age=60", ...headers } });
const DISCOVERY_LINKS = `</.well-known/api-catalog>; rel="api-catalog"; type="application/linkset+json", </openapi.json>; rel="service-desc"; type="application/openapi+json", </.well-known/mcp/server-card.json>; rel="service-meta"; type="application/json", </llms.txt>; rel="describedby"; type="text/plain"`;
const esc = (s="") => String(s).replace(/[&<>"']/g, c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const iso = () => new Date().toISOString();
const safeSlug = s => String(s||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,120);
function bytesToB64(bytes){let s=""; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function hmac(secret, value){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return bytesToB64(new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(value))))}
async function digest(value){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function isAdmin(request, env){
  const auth=request.headers.get("authorization")||"";
  if(env.ADMIN_TOKEN && auth.startsWith("Bearer ") && auth.slice(7)===env.ADMIN_TOKEN) return true;
  const raw=(request.headers.get("cookie")||"").split(/;\s*/).find(x=>x.startsWith("emin_session="))?.slice(13);
  if(!raw||!env.ADMIN_SESSION_SECRET)return false;
  const [expiry,sig]=raw.split("."); if(!expiry||Date.now()>Number(expiry))return false;
  return sig===await hmac(env.ADMIN_SESSION_SECRET,expiry);
}
async function requireAdmin(request,env){return await isAdmin(request,env)?null:json({error:"Unauthorized"},401)}
async function publicArticles(env,{kind,query,limit=100}={}){let where="status='published'",args=[];if(kind&&KINDS.includes(kind)){where+=" AND kind=?";args.push(kind)}if(query){where+=" AND (title LIKE ? OR summary LIKE ? OR body LIKE ?)";const q=`%${query}%`;args.push(q,q,q)}return (await env.DB.prepare(`SELECT * FROM articles WHERE ${where} ORDER BY COALESCE(published_at,created_at) DESC LIMIT ?`).bind(...args,Math.min(Number(limit)||100,500)).all()).results}
async function getArticle(env,idOrSlug,includeDraft=false){const where=includeDraft?"(id=? OR slug=?) AND status!='deleted'":"(id=? OR slug=?) AND status='published'";return await env.DB.prepare(`SELECT * FROM articles WHERE ${where} LIMIT 1`).bind(idOrSlug,idOrSlug).first()}
function page({title="Emin",description="Writing, film, photography, code, and music by Emin Mahrt.",body,canonical=ORIGIN,image=""}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${image?`<meta property="og:image" content="${esc(image)}">`:""}<meta name="twitter:card" content="summary_large_image"><link rel="alternate" type="application/rss+xml" href="/rss.xml"><link rel="alternate" type="application/feed+json" href="/feed.json"><style>${CSS}</style><script>${WEBMCP}</script></head><body><header><a class="brand" href="/">EMIN.</a><nav>${KINDS.map(k=>`<a href="/${k}">${KIND_LABELS[k]}</a>`).join("")}<a href="/about">About</a></nav></header>${body}<footer><strong>EMIN.</strong><span>Berlin · Human-made work, machine-readable.</span><nav><a href="/llms.txt">LLMs</a><a href="/openapi.json">API</a><a href="/.well-known/mcp/server-card.json">MCP</a></nav></footer></body></html>`}
const WEBMCP=`document.addEventListener("DOMContentLoaded",()=>{if(navigator.modelContext?.provideContext){navigator.modelContext.provideContext({tools:[{name:"search_work",description:"Search Emin’s published work",inputSchema:{type:"object",properties:{query:{type:"string"},kind:{type:"string"}}},execute:async({query="",kind=""})=>fetch("/api/articles?query="+encodeURIComponent(query)+"&kind="+encodeURIComponent(kind)).then(r=>r.json())},{name:"list_work",description:"List Emin’s published work",inputSchema:{type:"object",properties:{kind:{type:"string"},limit:{type:"integer"}}},execute:async({kind="",limit=100})=>fetch("/api/articles?kind="+encodeURIComponent(kind)+"&limit="+limit).then(r=>r.json())},{name:"get_work",description:"Read one work by ID",inputSchema:{type:"object",required:["id"],properties:{id:{type:"string"}}},execute:async({id})=>fetch("/api/articles/"+encodeURIComponent(id)).then(r=>r.json())}]})}});`;
const CSS=`:root{--paper:#f4f0e7;--ink:#191713;--hot:#ff5a1f;--lime:#dfff45;--line:#beb7a8}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}a{color:inherit}header,footer{display:flex;align-items:center;justify-content:space-between;gap:2rem;padding:1.25rem 4vw;border-bottom:1px solid var(--line)}footer{border-top:1px solid var(--line);border-bottom:0;margin-top:5rem;flex-wrap:wrap}.brand{font-size:1.6rem;font-weight:900;text-decoration:none;letter-spacing:-.06em}nav{display:flex;gap:1.2rem;flex-wrap:wrap}nav a{text-decoration:none;font-size:.9rem}.hero{min-height:68vh;padding:7vw 4vw;display:grid;align-content:center;border-bottom:1px solid var(--line)}.eyebrow{text-transform:uppercase;letter-spacing:.15em;font-size:.72rem;font-weight:800}.hero h1{font-size:clamp(3.8rem,11vw,10rem);line-height:.82;letter-spacing:-.075em;margin:.3em 0;max-width:12ch}.hero h1 em{color:var(--hot);font-style:normal}.hero p{font-size:clamp(1.1rem,2vw,1.5rem);max-width:42rem}.areas,.work{padding:5rem 4vw}.areas h2,.work h2{font-size:clamp(2.4rem,5vw,5rem);letter-spacing:-.055em;line-height:.95}.area-grid,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));border-left:1px solid var(--line);border-top:1px solid var(--line)}.area,.card{padding:1.5rem;border-right:1px solid var(--line);border-bottom:1px solid var(--line);text-decoration:none;min-height:180px}.area strong{display:block;font-size:2rem;margin-top:2.5rem}.card h3{font-size:1.4rem;line-height:1.1}.card p{color:#5c574e}.tag{font-size:.7rem;text-transform:uppercase;letter-spacing:.12em;font-weight:800;color:var(--hot)}.article{max-width:780px;margin:0 auto;padding:7rem 1.25rem}.article h1{font-size:clamp(2.8rem,7vw,6rem);line-height:.95;letter-spacing:-.06em}.article .dek{font-size:1.25rem;color:#5c574e}.prose{font-family:Georgia,serif;font-size:1.1rem}.prose h2,.prose h3{font-family:Inter,system-ui,sans-serif;margin-top:2.5em}.prose img{max-width:100%;height:auto}.prose a{text-decoration-color:var(--hot)}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}.hero{min-height:60vh;padding-top:4rem}.article{padding-top:4rem}}`;
function card(a){return `<a class="card" href="/${a.kind}/${esc(a.slug)}"><span class="tag">${esc(KIND_LABELS[a.kind]||a.kind)} · ${esc((a.published_at||a.created_at||"").slice(0,10))}</span><h3>${esc(a.title)}</h3><p>${esc(a.summary||"")}</p></a>`}
async function renderHome(env,request){const items=await publicArticles(env,{limit:12});if((request.headers.get("accept")||"").includes("text/markdown")){const md=`# Emin Mahrt\n\nWriting, film, photography, code, and music. One body of work—for people, search engines, and agents.\n\n## Areas\n${KINDS.map(k=>`- [${KIND_LABELS[k]}](${ORIGIN}/${k})`).join("\n")}\n\n## Recent work\n${items.map(a=>`- [${a.title}](${ORIGIN}/${a.kind}/${a.slug}) — ${a.summary}`).join("\n")}`;return text(md,"text/markdown; charset=utf-8",200,{"x-markdown-tokens":String(Math.ceil(md.length/4)),"link":DISCOVERY_LINKS,"vary":"Accept"})}return text(page({body:`<main><section class="hero"><span class="eyebrow">Emin Mahrt · Berlin</span><h1>I make things that <em>move.</em></h1><p>Writing, film, photography, code, and music. One body of work—for people, search engines, and agents.</p></section><section class="areas"><span class="eyebrow">Five practices</span><h2>Explore the work.</h2><div class="area-grid">${KINDS.map((k,i)=>`<a class="area" href="/${k}"><span>0${i+1}</span><strong>${KIND_LABELS[k]}</strong></a>`).join("")}</div></section><section class="work"><span class="eyebrow">Selected</span><h2>Recent work.</h2><div class="grid">${items.map(card).join("")}</div></section></main>`}),"text/html; charset=utf-8",200,{"link":DISCOVERY_LINKS,"vary":"Accept"})}
async function renderKind(env,kind){const items=await publicArticles(env,{kind,limit:200});return text(page({title:`${KIND_LABELS[kind]} — Emin`,description:`${KIND_LABELS[kind]} by Emin Mahrt.`,canonical:`${ORIGIN}/${kind}`,body:`<main class="work"><span class="eyebrow">${esc(KIND_LABELS[kind])}</span><h2>${esc(KIND_LABELS[kind])}.</h2><div class="grid">${items.map(card).join("")}</div></main>`}),"text/html; charset=utf-8")}
async function renderArticle(env,kind,slug){const a=await env.DB.prepare("SELECT * FROM articles WHERE kind=? AND slug=? AND status='published' LIMIT 1").bind(kind,slug).first();if(!a)return text(page({title:"Not found — Emin",body:'<main class="article"><h1>Not found.</h1></main>'}),"text/html; charset=utf-8",404);marked.setOptions({gfm:true,breaks:false});const html=await marked.parse(a.body);return text(page({title:`${a.title} — Emin`,description:a.summary,canonical:`${ORIGIN}/${a.kind}/${a.slug}`,image:a.image_url,body:`<main><article class="article"><span class="tag">${esc(KIND_LABELS[a.kind])}</span><h1>${esc(a.title)}</h1><p class="dek">${esc(a.summary)}</p><div class="prose">${html}</div></article></main>`}),"text/html; charset=utf-8")}
function articleRecord(a,full=true){const x={id:a.id,title:a.title,slug:a.slug,kind:a.kind,language:a.language,summary:a.summary,status:a.status,source_url:a.source_url,image_url:a.image_url,created_at:a.created_at,updated_at:a.updated_at,published_at:a.published_at,url:`${ORIGIN}/${a.kind}/${a.slug}`,markdown_url:`${ORIGIN}/api/articles/${a.id}.md`,json_url:`${ORIGIN}/api/articles/${a.id}`};if(full)x.body=a.body;return x}
async function adminApi(request,env,path){const auth=await requireAdmin(request,env);if(path==="/api/admin/me")return json({authenticated:!auth});if(path==="/api/admin/login"&&request.method==="POST"){const b=await request.json();const ok=b.username===(env.ADMIN_USERNAME||"admin")&&await digest(b.password||"")===env.ADMIN_PASSWORD_HASH;if(!ok)return json({error:"Invalid credentials"},401);const expiry=String(Date.now()+1000*60*60*24*14),sig=await hmac(env.ADMIN_SESSION_SECRET,expiry);return json({ok:true},200,{"set-cookie":`emin_session=${expiry}.${sig}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=1209600`})}if(path==="/api/admin/logout"&&request.method==="POST")return json({ok:true},200,{"set-cookie":"emin_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"});if(auth)return auth;
  if(path==="/api/admin/articles"&&request.method==="GET"){const rows=(await env.DB.prepare("SELECT * FROM articles WHERE status!='deleted' ORDER BY updated_at DESC LIMIT 1000").all()).results;return json({articles:rows.map(x=>articleRecord(x,true))})}
  if(path==="/api/admin/articles"&&request.method==="POST"){const b=await request.json(),now=iso(),id=crypto.randomUUID(),slug=safeSlug(b.slug||b.title);if(!b.title||!slug||!b.body)return json({error:"Title, slug, and body are required"},400);const status=b.status==="published"?"published":"draft";await env.DB.prepare("INSERT INTO articles(id,title,slug,kind,language,summary,body,status,source_url,image_url,created_at,updated_at,published_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,b.title,slug,KINDS.includes(b.kind)?b.kind:"write",b.language||"en",b.summary||"",b.body,status,b.source_url||"",b.image_url||"",now,now,status==="published"?now:null).run();return json({article:articleRecord(await getArticle(env,id,true),true)},201)}
  const match=path.match(/^\/api\/admin\/articles\/([^/]+)$/);if(match&&request.method==="PUT"){const old=await getArticle(env,match[1],true);if(!old)return json({error:"Not found"},404);const b=await request.json(),status=b.status==="published"?"published":"draft",published=status==="published"?(old.published_at||iso()):null;await env.DB.prepare("UPDATE articles SET title=?,slug=?,kind=?,language=?,summary=?,body=?,status=?,source_url=?,image_url=?,updated_at=?,published_at=? WHERE id=?").bind(b.title||old.title,safeSlug(b.slug||old.slug),KINDS.includes(b.kind)?b.kind:old.kind,b.language||old.language,b.summary??old.summary,b.body??old.body,status,b.source_url??old.source_url,b.image_url??old.image_url,iso(),published,old.id).run();return json({article:articleRecord(await getArticle(env,old.id,true),true)})}if(match&&request.method==="DELETE"){await env.DB.prepare("UPDATE articles SET status='deleted',updated_at=? WHERE id=?").bind(iso(),match[1]).run();return json({ok:true})}return json({error:"Not found"},404)}
const TOOL_DEFS=[{name:"search_work",description:"Search published work",inputSchema:{type:"object",properties:{query:{type:"string"},kind:{type:"string",enum:KINDS}}}},{name:"list_work",description:"List published work",inputSchema:{type:"object",properties:{kind:{type:"string",enum:KINDS},limit:{type:"integer"}}}},{name:"get_work",description:"Get one published work by ID or slug",inputSchema:{type:"object",required:["id"],properties:{id:{type:"string"}}}},{name:"create_draft",description:"Create a private draft; requires bearer token",inputSchema:{type:"object",required:["title","body"],properties:{title:{type:"string"},body:{type:"string"},summary:{type:"string"},kind:{type:"string",enum:KINDS},slug:{type:"string"}}}},{name:"update_work",description:"Update work; requires bearer token",inputSchema:{type:"object",required:["id"],properties:{id:{type:"string"},title:{type:"string"},body:{type:"string"},summary:{type:"string"},kind:{type:"string",enum:KINDS},slug:{type:"string"},status:{type:"string",enum:["draft","published"]}}}},{name:"publish_work",description:"Publish a draft; requires bearer token",inputSchema:{type:"object",required:["id"],properties:{id:{type:"string"}}}},{name:"delete_work",description:"Move work to recoverable trash; requires bearer token",inputSchema:{type:"object",required:["id"],properties:{id:{type:"string"}}}}];
const mcpResult=value=>({content:[{type:"text",text:JSON.stringify(value,null,2)}],structuredContent:value});
async function handleMcp(request,env){if(request.method!=="POST")return json({name:"emin-writing",protocol:"MCP Streamable HTTP",endpoint:`${ORIGIN}/mcp`,tools:TOOL_DEFS.map(x=>x.name)});const r=await request.json(),reply=result=>json({jsonrpc:"2.0",id:r.id,result});if(r.method==="initialize")return reply({protocolVersion:r.params?.protocolVersion||"2025-06-18",capabilities:{tools:{listChanged:false}},serverInfo:{name:"emin-writing",version:"1.0.0"},instructions:"Search and cite Emin's published work. Mutations require authorization."});if(r.method==="notifications/initialized")return new Response(null,{status:202});if(r.method==="tools/list")return reply({tools:TOOL_DEFS});if(r.method==="tools/call"){const n=r.params?.name,a=r.params?.arguments||{};if(n==="search_work"||n==="list_work")return reply(mcpResult((await publicArticles(env,{query:n==="search_work"?a.query:null,kind:a.kind,limit:a.limit||100})).map(x=>articleRecord(x,false))));if(n==="get_work"){const x=await getArticle(env,a.id);return reply(mcpResult(x?articleRecord(x,true):{error:"Not found"}))}if(!await isAdmin(request,env))return json({jsonrpc:"2.0",id:r.id,error:{code:-32001,message:"Unauthorized"}},401);if(n==="create_draft"){const fake=new Request(`${ORIGIN}/api/admin/articles`,{method:"POST",headers:request.headers,body:JSON.stringify({...a,status:"draft"})});const res=await adminApi(fake,env,"/api/admin/articles");return reply(mcpResult(await res.json()))}const old=await getArticle(env,a.id,true);if(!old)return reply(mcpResult({error:"Not found"}));if(n==="delete_work"){await env.DB.prepare("UPDATE articles SET status='deleted',updated_at=? WHERE id=?").bind(iso(),old.id).run();return reply(mcpResult({ok:true,id:old.id}))}if(n==="publish_work")a.status="published";if(n==="update_work"||n==="publish_work"){const b={...old,...a};const fake=new Request(`${ORIGIN}/api/admin/articles/${old.id}`,{method:"PUT",headers:request.headers,body:JSON.stringify(b)});const res=await adminApi(fake,env,`/api/admin/articles/${old.id}`);return reply(mcpResult(await res.json()))}}return json({jsonrpc:"2.0",id:r.id,error:{code:-32601,message:"Method not found"}},404)}
function openapi(){return {openapi:"3.1.0",info:{title:"Emin Work API",version:"1.0.0",description:"Public reads and authenticated publishing for Emin's canonical work library."},servers:[{url:ORIGIN}],paths:{"/api/articles":{get:{operationId:"listWork",responses:{200:{description:"Published work"}}}},"/api/articles/{id}":{get:{operationId:"getWork",responses:{200:{description:"One published work"}}}},"/mcp":{post:{operationId:"mcp",responses:{200:{description:"MCP JSON-RPC"}}}}}}}
async function feeds(env,type){const rows=await publicArticles(env,{limit:50});if(type==="json")return json({version:"https://jsonfeed.org/version/1.1",title:"Emin",home_page_url:ORIGIN,feed_url:`${ORIGIN}/feed.json`,items:rows.map(a=>({id:a.id,url:`${ORIGIN}/${a.kind}/${a.slug}`,title:a.title,summary:a.summary,content_text:a.body,date_published:a.published_at}))});return text(`<?xml version="1.0"?><rss version="2.0"><channel><title>Emin</title><link>${ORIGIN}</link><description>Writing, film, photography, code, and music by Emin Mahrt.</description>${rows.map(a=>`<item><guid>${a.id}</guid><title><![CDATA[${a.title}]]></title><link>${ORIGIN}/${a.kind}/${a.slug}</link><description><![CDATA[${a.summary}]]></description><pubDate>${new Date(a.published_at||a.created_at).toUTCString()}</pubDate></item>`).join("")}</channel></rss>`,"application/rss+xml; charset=utf-8")}
export async function onRequest(context){const {request,env}=context,url=new URL(request.url),path=url.pathname;
  try{
    if(path==="/admin"||path==="/admin/")return context.next();
    if(path.startsWith("/assets/"))return context.next();
    if(path.startsWith("/api/admin/"))return adminApi(request,env,path);
    if(path==="/mcp")return handleMcp(request,env);
    if(path==="/api/articles"&&request.method==="GET"){const rows=await publicArticles(env,{kind:url.searchParams.get("kind"),query:url.searchParams.get("query"),limit:url.searchParams.get("limit")});return json({articles:rows.map(x=>articleRecord(x,false)),count:rows.length})}
    const md=path.match(/^\/api\/articles\/([^/]+)\.md$/);if(md){const a=await getArticle(env,md[1]);return a?text(a.body,"text/markdown; charset=utf-8"):json({error:"Not found"},404)}
    const one=path.match(/^\/api\/articles\/([^/]+)$/);if(one){const a=await getArticle(env,one[1]);return a?json(articleRecord(a,true)):json({error:"Not found"},404)}
    if(path==="/openapi.json")return json(openapi());
    if(path==="/rss.xml")return feeds(env,"rss"); if(path==="/feed.json")return feeds(env,"json");
    if(path==="/robots.txt")return text("User-agent: *\nAllow: /\nContent-Signal: ai-train=no, search=yes, ai-input=yes\nSitemap: https://writing.emin.de/sitemap.xml\n\nUser-agent: GPTBot\nAllow: /\nContent-Signal: ai-train=no, search=yes, ai-input=yes\nUser-agent: ClaudeBot\nAllow: /\nContent-Signal: ai-train=no, search=yes, ai-input=yes\nUser-agent: Google-Extended\nAllow: /\nContent-Signal: ai-train=no, search=yes, ai-input=yes\n");
    if(path==="/sitemap.xml"){const rows=await publicArticles(env,{limit:500});return text(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${ORIGIN}/</loc></url>${KINDS.map(k=>`<url><loc>${ORIGIN}/${k}</loc></url>`).join("")}${rows.map(a=>`<url><loc>${ORIGIN}/${a.kind}/${a.slug}</loc><lastmod>${a.updated_at.slice(0,10)}</lastmod></url>`).join("")}</urlset>`,"application/xml; charset=utf-8")}
    if(path==="/llms.txt")return text(`# Emin Mahrt\n\nCanonical portfolio and publishing system for Emin Mahrt.\n\n## Areas\n- Writing: ${ORIGIN}/write\n- Film: ${ORIGIN}/film\n- Photography: ${ORIGIN}/photo\n- Code: ${ORIGIN}/code\n- Music: ${ORIGIN}/music\n\n## Machine access\n- MCP: ${ORIGIN}/mcp\n- API: ${ORIGIN}/openapi.json\n- JSON Feed: ${ORIGIN}/feed.json\n- RSS: ${ORIGIN}/rss.xml\n\nPublished HTML, Markdown, JSON, feeds, API, and MCP are generated from the same canonical D1 records.`,"text/plain; charset=utf-8");
    if(path==="/llms-full.txt"){const rows=await publicArticles(env,{limit:500});return text(`# Emin Mahrt — Complete published work\n\n${rows.map(a=>`## ${a.title}\nURL: ${ORIGIN}/${a.kind}/${a.slug}\nArea: ${a.kind}\n\n${a.summary}\n\n${a.body}`).join("\n\n---\n\n")}`,"text/plain; charset=utf-8")}
    if(path==="/.well-known/mcp/server-card.json"||path==="/.well-known/webmcp.json")return json({name:"emin-writing",version:"1.0.0",description:"Search, read, draft, update, publish, and delete Emin's work.",transport:{type:"streamable-http",url:`${ORIGIN}/mcp`},authentication:{public_tools:["search_work","list_work","get_work"],write_tools:"Bearer token"},tools:TOOL_DEFS.map(x=>x.name)});
    if(path==="/.well-known/agent-card.json")return json({name:"Emin's Work",description:"Canonical, cited access to work by Emin Mahrt.",url:ORIGIN,capabilities:{streaming:false,pushNotifications:false},defaultInputModes:["text"],defaultOutputModes:["text","application/json","text/markdown"]});
    if(path==="/.well-known/agent-skills/index.json")return json({skills:[{id:"emin-work",name:"Browse Emin's work",description:"Search and retrieve writing, film, photography, code, and music.",url:`${ORIGIN}/skill.md`}]});
    if(path==="/skill.md")return text(`# Emin Work Skill\n\nUse when a user asks about work by Emin Mahrt. Search with the public MCP tool search_work, then retrieve exact records with get_work. Cite the canonical URL. Never claim unpublished work exists.`,"text/markdown; charset=utf-8");
    if(path==="/.well-known/api-catalog")return text(JSON.stringify({linkset:[{anchor:ORIGIN,"service-desc":[{href:`${ORIGIN}/openapi.json`,type:"application/openapi+json"}],"service-doc":[{href:`${ORIGIN}/llms.txt`,type:"text/plain"}],status:[{href:`${ORIGIN}/api/articles?limit=1`,type:"application/json"}]},{anchor:`${ORIGIN}/mcp`,"service-desc":[{href:`${ORIGIN}/.well-known/mcp/server-card.json`,type:"application/json"}]}]},null,2),"application/linkset+json; charset=utf-8");
    if(path==="/.well-known/oauth-authorization-server")return json({issuer:url.origin,authorization_endpoint:`${url.origin}/admin/`,token_endpoint:`${url.origin}/api/admin/login`,grant_types_supported:["password"],token_endpoint_auth_methods_supported:["none"],scopes_supported:["content:read","content:write","content:publish"],agent_auth:{register_uri:`${url.origin}/auth.md`,supported_identity_types:["human-admin"],credential_types:["session-cookie","bearer-token"]}});
    if(path==="/.well-known/oauth-protected-resource")return json({resource:url.origin,authorization_servers:[url.origin],scopes_supported:["content:read","content:write","content:publish"],bearer_methods_supported:["header"]});
    if(path==="/auth.md")return text(`# Auth.md\n\n## Agent authentication\n\nPublic tools search_work, list_work, and get_work require no authentication. Write tools create_draft, update_work, publish_work, and delete_work require an administrator-issued bearer token in the Authorization header.\n\n## Registration\n\nAutomated public registration is not offered. The owner creates and revokes credentials privately.\n\n- Protected resource metadata: ${url.origin}/.well-known/oauth-protected-resource\n- Authorization server metadata: ${url.origin}/.well-known/oauth-authorization-server`,"text/markdown; charset=utf-8");
    if(path==="/.well-known/commerce.json")return json({version:"1.0",offers:[],checkout:false,description:"No products or payment rails are currently offered."});
    if(path==="/about")return text(page({title:"About — Emin",canonical:`${ORIGIN}/about`,body:'<main class="article"><span class="eyebrow">About</span><h1>Emin Mahrt.</h1><p class="dek">I write, make films and photographs, build software, and make music in Berlin.</p><div class="prose"><p>This site keeps the human page and machine-readable record together. Every published work is available as semantic HTML, Markdown, JSON, feeds, API, and MCP from one canonical source.</p></div></main>'}),"text/html; charset=utf-8");
    if(path==="/")return renderHome(env,request);const bits=path.split("/").filter(Boolean);if(bits.length===1&&KINDS.includes(bits[0]))return renderKind(env,bits[0]);if(bits.length===2&&KINDS.includes(bits[0]))return renderArticle(env,bits[0],bits[1]);return text(page({title:"Not found — Emin",body:'<main class="article"><h1>Not found.</h1></main>'}),"text/html; charset=utf-8",404);
  }catch(error){console.error(JSON.stringify({path,error:error.message}));return json({error:"Internal error"},500)}
}
